# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '0.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(999, 450)
        self.gridLayoutWidget = QtWidgets.QWidget(Dialog)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(80, 150, 871, 251))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.n_degree = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.n_degree.setObjectName("n_degree")
        self.buttonGroup = QtWidgets.QButtonGroup(Dialog)
        self.buttonGroup.setObjectName("buttonGroup")
        self.buttonGroup.addButton(self.n_degree)
        self.gridLayout.addWidget(self.n_degree, 3, 0, 1, 1)
        self.cos = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.cos.setObjectName("cos")
        self.buttonGroup.addButton(self.cos)
        self.gridLayout.addWidget(self.cos, 0, 1, 1, 1)
        self.cube = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.cube.setObjectName("cube")
        self.buttonGroup.addButton(self.cube)
        self.gridLayout.addWidget(self.cube, 3, 1, 1, 1)
        self.pi = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.pi.setObjectName("pi")
        self.buttonGroup.addButton(self.pi)
        self.gridLayout.addWidget(self.pi, 3, 7, 1, 1)
        self.perc = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.perc.setObjectName("perc")
        self.buttonGroup.addButton(self.perc)
        self.gridLayout.addWidget(self.perc, 3, 3, 1, 1)
        self.plus_minus = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.plus_minus.setObjectName("plus_minus")
        self.buttonGroup.addButton(self.plus_minus)
        self.gridLayout.addWidget(self.plus_minus, 3, 5, 1, 1)
        self.n_to_ten = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.n_to_ten.setObjectName("n_to_ten")
        self.buttonGroup.addButton(self.n_to_ten)
        self.gridLayout.addWidget(self.n_to_ten, 9, 5, 1, 1)
        self.un_perc = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.un_perc.setObjectName("un_perc")
        self.buttonGroup.addButton(self.un_perc)
        self.gridLayout.addWidget(self.un_perc, 9, 3, 1, 1)
        self.square = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.square.setObjectName("square")
        self.buttonGroup.addButton(self.square)
        self.gridLayout.addWidget(self.square, 3, 2, 1, 1)
        self.one_division = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.one_division.setObjectName("one_division")
        self.buttonGroup.addButton(self.one_division)
        self.gridLayout.addWidget(self.one_division, 13, 0, 1, 1)
        self.ten_degree = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.ten_degree.setObjectName("ten_degree")
        self.buttonGroup.addButton(self.ten_degree)
        self.gridLayout.addWidget(self.ten_degree, 13, 2, 1, 1)
        self.anti_cube = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.anti_cube.setObjectName("anti_cube")
        self.buttonGroup.addButton(self.anti_cube)
        self.gridLayout.addWidget(self.anti_cube, 9, 0, 1, 1)
        self.double_degree = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.double_degree.setObjectName("double_degree")
        self.buttonGroup.addButton(self.double_degree)
        self.gridLayout.addWidget(self.double_degree, 13, 1, 1, 1)
        self.log = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.log.setObjectName("log")
        self.buttonGroup.addButton(self.log)
        self.gridLayout.addWidget(self.log, 13, 3, 1, 1)
        self.clear = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.clear.setObjectName("clear")
        self.buttonGroup.addButton(self.clear)
        self.gridLayout.addWidget(self.clear, 0, 5, 1, 1)
        self.rad_deg = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.rad_deg.setObjectName("rad_deg")
        self.buttonGroup.addButton(self.rad_deg)
        self.gridLayout.addWidget(self.rad_deg, 3, 6, 1, 1)
        self.tan = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.tan.setObjectName("tan")
        self.buttonGroup.addButton(self.tan)
        self.gridLayout.addWidget(self.tan, 0, 2, 1, 1)
        self.save_colors = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.save_colors.setObjectName("save_colors")
        self.buttonGroup.addButton(self.save_colors)
        self.gridLayout.addWidget(self.save_colors, 9, 8, 1, 1)
        self.change_col = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.change_col.setObjectName("change_col")
        self.buttonGroup.addButton(self.change_col)
        self.gridLayout.addWidget(self.change_col, 3, 8, 1, 1)
        self.sin = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.sin.setObjectName("sin")
        self.buttonGroup.addButton(self.sin)
        self.gridLayout.addWidget(self.sin, 0, 0, 1, 1)
        self.save_txt = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.save_txt.setObjectName("save_txt")
        self.buttonGroup.addButton(self.save_txt)
        self.gridLayout.addWidget(self.save_txt, 13, 8, 1, 1)
        self.load_colors = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.load_colors.setObjectName("load_colors")
        self.buttonGroup.addButton(self.load_colors)
        self.gridLayout.addWidget(self.load_colors, 0, 8, 1, 1)
        self.e = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.e.setObjectName("e")
        self.buttonGroup.addButton(self.e)
        self.gridLayout.addWidget(self.e, 0, 7, 1, 1)
        self.cotangent = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.cotangent.setObjectName("cotangent")
        self.buttonGroup.addButton(self.cotangent)
        self.gridLayout.addWidget(self.cotangent, 0, 3, 1, 1)
        self.clear_all = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.clear_all.setObjectName("clear_all")
        self.buttonGroup.addButton(self.clear_all)
        self.gridLayout.addWidget(self.clear_all, 0, 6, 1, 1)
        self.division = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.division.setObjectName("division")
        self.buttonGroup.addButton(self.division)
        self.gridLayout.addWidget(self.division, 13, 7, 1, 1)
        self.module = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.module.setObjectName("module")
        self.buttonGroup.addButton(self.module)
        self.gridLayout.addWidget(self.module, 13, 5, 1, 1)
        self.multiplication = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.multiplication.setObjectName("multiplication")
        self.buttonGroup.addButton(self.multiplication)
        self.gridLayout.addWidget(self.multiplication, 13, 6, 1, 1)
        self.minus = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.minus.setObjectName("minus")
        self.buttonGroup.addButton(self.minus)
        self.gridLayout.addWidget(self.minus, 9, 7, 1, 1)
        self.plus = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.plus.setObjectName("plus")
        self.buttonGroup.addButton(self.plus)
        self.gridLayout.addWidget(self.plus, 9, 6, 1, 1)
        self.factorial = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.factorial.setObjectName("factorial")
        self.buttonGroup.addButton(self.factorial)
        self.gridLayout.addWidget(self.factorial, 9, 1, 1, 1)
        self.anti_square = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.anti_square.setObjectName("anti_square")
        self.buttonGroup.addButton(self.anti_square)
        self.gridLayout.addWidget(self.anti_square, 9, 2, 1, 1)
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setGeometry(QtCore.QRect(470, 90, 16, 21))
        self.label.setObjectName("label")
        self.first = QtWidgets.QLineEdit(Dialog)
        self.first.setGeometry(QtCore.QRect(220, 90, 113, 20))
        self.first.setObjectName("first")
        self.second = QtWidgets.QLineEdit(Dialog)
        self.second.setGeometry(QtCore.QRect(350, 90, 110, 20))
        self.second.setObjectName("second")
        self.answer = QtWidgets.QLineEdit(Dialog)
        self.answer.setGeometry(QtCore.QRect(496, 90, 331, 20))
        self.answer.setReadOnly(True)
        self.answer.setObjectName("answer")
        self.degree = QtWidgets.QRadioButton(Dialog)
        self.degree.setGeometry(QtCore.QRect(370, 23, 82, 17))
        self.degree.setObjectName("degree")
        self.buttonGroup_2 = QtWidgets.QButtonGroup(Dialog)
        self.buttonGroup_2.setObjectName("buttonGroup_2")
        self.buttonGroup_2.addButton(self.degree)
        self.radians = QtWidgets.QRadioButton(Dialog)
        self.radians.setGeometry(QtCore.QRect(370, 40, 82, 20))
        self.radians.setObjectName("radians")
        self.buttonGroup_2.addButton(self.radians)
        self.verticalLayoutWidget = QtWidgets.QWidget(Dialog)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(10, 10, 341, 53))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.info_1 = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.info_1.setObjectName("info_1")
        self.verticalLayout.addWidget(self.info_1)
        self.info_2 = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.info_2.setObjectName("info_2")
        self.verticalLayout.addWidget(self.info_2)
        self.info_3 = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.info_3.setObjectName("info_3")
        self.verticalLayout.addWidget(self.info_3)
        self.label_5 = QtWidgets.QLabel(Dialog)
        self.label_5.setGeometry(QtCore.QRect(250, 70, 61, 16))
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(Dialog)
        self.label_6.setGeometry(QtCore.QRect(350, 70, 131, 16))
        self.label_6.setObjectName("label_6")
        self.label_7 = QtWidgets.QLabel(Dialog)
        self.label_7.setGeometry(QtCore.QRect(640, 70, 47, 13))
        self.label_7.setObjectName("label_7")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.n_degree.setText(_translate("Dialog", "x^n"))
        self.cos.setText(_translate("Dialog", "cos"))
        self.cube.setText(_translate("Dialog", "x^3"))
        self.pi.setText(_translate("Dialog", "pi"))
        self.perc.setText(_translate("Dialog", "%"))
        self.plus_minus.setText(_translate("Dialog", "+-"))
        self.n_to_ten.setText(_translate("Dialog", "n to10"))
        self.un_perc.setText(_translate("Dialog", "перевод из %"))
        self.square.setText(_translate("Dialog", "x^2"))
        self.one_division.setText(_translate("Dialog", "1/x"))
        self.ten_degree.setText(_translate("Dialog", "10^x"))
        self.anti_cube.setText(_translate("Dialog", "3Vx"))
        self.double_degree.setText(_translate("Dialog", "2^x"))
        self.log.setText(_translate("Dialog", "log"))
        self.clear.setText(_translate("Dialog", "C"))
        self.rad_deg.setText(_translate("Dialog", "Rad<->Deg"))
        self.tan.setText(_translate("Dialog", "tg"))
        self.save_colors.setText(_translate("Dialog", "Сохранить цвета в файл (config.cnf)"))
        self.change_col.setText(_translate("Dialog", "Изменить цвета "))
        self.sin.setText(_translate("Dialog", "sin"))
        self.save_txt.setText(_translate("Dialog", "Сохранить результат в answer.txt"))
        self.load_colors.setText(_translate("Dialog", "Загрузить цвета"))
        self.e.setText(_translate("Dialog", "e"))
        self.cotangent.setText(_translate("Dialog", "ctg"))
        self.clear_all.setText(_translate("Dialog", "CE"))
        self.division.setText(_translate("Dialog", ":"))
        self.module.setText(_translate("Dialog", "|x|"))
        self.multiplication.setText(_translate("Dialog", "*"))
        self.minus.setText(_translate("Dialog", "-"))
        self.plus.setText(_translate("Dialog", "+"))
        self.factorial.setText(_translate("Dialog", "n!"))
        self.anti_square.setText(_translate("Dialog", "2Vx"))
        self.label.setText(_translate("Dialog", "="))
        self.degree.setText(_translate("Dialog", "DEGREE"))
        self.radians.setText(_translate("Dialog", "RADIANS"))
        self.info_1.setText(_translate("Dialog", "Если вы собираетесь использовать тригонометрические функции"))
        self.info_2.setText(_translate("Dialog", " переводить градусы в радианы "))
        self.info_3.setText(_translate("Dialog", "(радианы в градусы) - укажите вводимую величину"))
        self.label_5.setText(_translate("Dialog", "I операнд"))
        self.label_6.setText(_translate("Dialog", "II операнд (опционально)"))
        self.label_7.setText(_translate("Dialog", "Ответ"))

